# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer2.org1.example.com:
  orderer3.org1.example.com:
  orderer4.org2.example.com:
  orderer5.org2.example.com:

networks:
  byfn:

services:

  orderer2.org1.example.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-org1-base
    container_name: orderer2.org1.example.com
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/peerOrganizations/org1.example.com/peers/orderer2.org1.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/peerOrganizations/org1.example.com/peers/orderer2.org1.example.com/tls:/var/hyperledger/orderer/tls
        - orderer2.org1.example.com:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.org1.example.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-org1-base
    container_name: orderer3.org1.example.com
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/peerOrganizations/org1.example.com/peers/orderer3.org1.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/peerOrganizations/org1.example.com/peers/orderer3.org1.example.com/tls:/var/hyperledger/orderer/tls
        - orderer3.org1.example.com:/var/hyperledger/production/orderer
    ports:
    - 9050:7050

  orderer4.org2.example.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-org2-base
    container_name: orderer4.org2.example.com
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/peerOrganizations/org2.example.com/peers/orderer4.org2.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/peerOrganizations/org2.example.com/peers/orderer4.org2.example.com/tls:/var/hyperledger/orderer/tls
        - orderer4.org2.example.com:/var/hyperledger/production/orderer
    ports:
    - 10050:7050

  orderer5.org2.example.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-org2-base
    container_name: orderer5.org2.example.com
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/peerOrganizations/org2.example.com/peers/orderer5.org2.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/peerOrganizations/org2.example.com/peers/orderer5.org2.example.com/tls:/var/hyperledger/orderer/tls
        - orderer5.org2.example.com:/var/hyperledger/production/orderer
        
    ports:
    - 11050:7050
